### ISSUE TITLE
Story 1: Fazer a denúncia

### ISSUE THREAD

**Issue by CristinaZayra** [CristinaZayra/Grupo-1-PDS#12]
Eu como cidadão desejo realizar uma denúncia de uma sinalização que está danificada, para que a prefeitura fique sabendo onde existe o problema e realize algo para o seu conserto. Posso selecionar qual o tipo da sinalização desejo denunciar, além de enviar uma foto do local e confirmarei minha localização no mapa.

**Critérios de Aceitação**
* Usuário preenche os dados da denúncia
* Todos os campos precisam ser preenchidos
* Garantir a integridade no envio da denúncia
* O envio da foto do local é opcional
* GPS confirma o local exato em que o cidadão está
* Confirmação do lugar via mensagem
* Usuário pode inserir comentário caso desejar apontar mais algum detalhe

**Tarefas**
- [x] Idealizar a interface específica dessa tela (1 hora)
- [x] Construir a interface desta story (1 hora)
- [x] Implementar a interface desta story (5 horas)
- [x] Pesquisar como usar a camera no aplicativo (2 horas)
- [x] Implementar a função de foto no aplicativo (5 horas)
- [x] Modelar banco de dados relacional (2 horas)
- [x] Criar banco de dados desta story (2 horas)
- [x] Conectar banco de dados a interface (5 horas)
- [x] Pesquisar opções da API para funcionalidades como GPS e sua conexão com o aplicativo (2 horas)
- [x] Integrar a API e suas funcionalidades. (5 horas)
- [x] Pesquisar o funcionamento do bootstrap (2 horas)
- [x] Integrar o bootstrap ao site (5 horas)
- [ ] Pesquisar sobre o certificado SSL e site de hospedagem que tenha suporte a SSL (2 horas)
- [ ] Hospedar o site no novo domínio e aplicar o certificado SSL (5 horas)
